// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsjsJUOo8CKpk-AuLSFGc6zYuJKFz1fs8',
    appId: '1:262497079999:android:2ef83e8555167eb73a6c0a',
    messagingSenderId: '262497079999',
    projectId: 'prayerbuddy-6ca4a',
    storageBucket: 'prayerbuddy-6ca4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATs7H8VicGU858YXsiAhEOQbxDzyxP2wI',
    appId: '1:262497079999:ios:31dc6074b126745c3a6c0a',
    messagingSenderId: '262497079999',
    projectId: 'prayerbuddy-6ca4a',
    storageBucket: 'prayerbuddy-6ca4a.firebasestorage.app',
    androidClientId: '262497079999-fthurl2d8gmg2i9rg1gj1clkq53i5jds.apps.googleusercontent.com',
    iosClientId: '262497079999-lrau3tfobup99aibg0ktsb3je4ed36dt.apps.googleusercontent.com',
    iosBundleId: 'com.example.prayerBuddy',
  );

}